#!/bin/bash
xhost +
#xterm -title "ms-embsys-app-mouseController" -hold -e "sudo python embsys-apps/ms-embsys-app-mouseController.py" &
xterm -title "ms-com" -hold -e "sudo python ms-com.py" & 
xterm -title "ms-ei" -hold -e "sudo python ms-ei.py"
