#!/bin/bash
#xterm -title "hTES" -hold -e "sudo tcpdump" &
#xterm -title "hTES" -hold -e "sudo tshark -i hTES-eth0" &
#xterm -title "hRx" -hold -e "sudo wireshark -i hRx-eth0" &

xterm -title "hRx2" -hold -e "sudo tshark -i hRx2-eth0" &


#xterm -title "vrepLoader" -hold -e "sudo python v-rep/vrepLoader.py" &
#sleep 10
#xterm -title "ss-embsys-app-vrep" -hold -e "sudo python embsys-apps/ss-embsys-app-vrep.py" 

#sudo python ss-com.py &
#sudo python v-rep/vrepLoader.py &
#sleep 10
#sudo python embsys-apps/ss-embsys-app-vrep.py & 

