#!/bin/bash
#xterm -title "hTES" -hold -e "sudo tcpdump" &
#xterm -title "hTES" -hold -e "sudo tshark -i hTES-eth0" &
#xterm -title "hTES" -hold -e "sudo wireshark -i hTES-eth0" &

sleep 5.1
xterm -title "hTEM" -hold -e "sudo ping 10.0.0.2 -c 1000 -i 10e-3" &


#xterm -title "vrepLoader" -hold -e "sudo python v-rep/vrepLoader.py" &
#sleep 10
#xterm -title "ss-embsys-app-vrep" -hold -e "sudo python embsys-apps/ss-embsys-app-vrep.py" 

#sudo python ss-com.py &
#sudo python v-rep/vrepLoader.py &
#sleep 10
#sudo python embsys-apps/ss-embsys-app-vrep.py & 

