#!/bin/bash
#xterm -title "hTES" -hold -e "sudo tcpdump" &
#xterm -title "hTES" -hold -e "sudo tshark -i hTES-eth0" &
sleep 5
xterm -title "hTx" -hold -e "sudo tcpreplay -i hTx-eth0 --loop=0 -K --mbps 100.0 ./scripts/test_modified.pcap" &


#xterm -title "vrepLoader" -hold -e "sudo python v-rep/vrepLoader.py" &
#sleep 10
#xterm -title "ss-embsys-app-vrep" -hold -e "sudo python embsys-apps/ss-embsys-app-vrep.py" 

#sudo python ss-com.py &
#sudo python v-rep/vrepLoader.py &
#sleep 10
#sudo python embsys-apps/ss-embsys-app-vrep.py & 

